server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /api
spring:
  application:
    name: jaccount-service
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    #    properties:
    #      hibernate:
    #        jdbc:
    #          time-zone: UTC
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: ${DISCOVERY_HOST}
cloudamqp:
  host: ${CLOUDAMQP_HOST}
  port: ${CLOUDAMQP_PORT}
  password: ${CLOUDAMQP_PASSWORD}
  username: ${CLOUDAMQP_USERNAME}
  virtual-host: ${CLOUDAMQP_VIRTUAL_HOST}
  queues:
    send-template-mail: send-template-mail-queue
jaccount:
  client:
    connect-timeout: 1m
    read-timeout: 10s
  service:
    email: ${SERVICE_MAIL_USERNAME}
    name: ${SERVICE_NAME:JustedlevHub}
    label: "{•...•}"
    host: ${SERVICE_HOST}