spring:
  jpa:
  #    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#springdoc:
#  swagger-ui:
#    config-url: /${spring.application.name}${server.servlet.context-path}/v3/api-docs/swagger-config
#    url: /${spring.application.name}${server.servlet.context-path}/v3/api-docs
jstorage:
  client:
    url: ${GATEWAY_HOST}/api/v1/
logging:
  level:
    web: debug
    sql: debug
    com.justedlev.hub: debug
    org.hibernate.orm.jdbc.bind: trace
app-config:
  activity-time: ${ACTIVITY_TIME:10m}
  offline-after-time: ${OFFLINE_AFTER_TIME:10m}
  service:
    url: ${GATEWAY_HOST}/${server.servlet.context-path}