server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

logging:
  file:
    name: ${logging.file.path}/latest.log
    path: ./.logs

spring:
  application:
    name: users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.endpoints.introspection}
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}
  devtools:
    restart:
      enabled: true
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: history
            audit_table_suffix: _history
            revision_field_name: rev_id
            revision_type_field_name: rev_type
            store_data_at_delete: true
            audit_table_prefix:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: users
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}

springdoc:
  swagger-ui:
    oauth:
      realm: ${keycloak.realm}
      client-id: ${keycloak.client.id}
      client-secret: ${keycloak.client.secret}
  show-actuator: true
  api-docs:
    version: openapi_3_1

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    app-group-name: justedlev-hub
    appname: users
  client:
    service-url:
      default-zone: ${configuration.service-registry.url}

management:
  info:
    build:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# Custom properties
cloudamqp:
  host: ${CLOUDAMQP_HOST}
  port: ${CLOUDAMQP_PORT}
  password: ${CLOUDAMQP_PASSWORD}
  username: ${CLOUDAMQP_USERNAME}
  virtual-host: ${CLOUDAMQP_VIRTUAL_HOST}
  queue:
    send-template-mail: send-template-mail-queue

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI}
  jwk-set-uri: ${KEYCLOAK_JWKS_URI}
  realm: ${KEYCLOAK_REALM}
  client:
    name:
    id: ${KEYCLOAK_CLIENT_ID}
    secret: ${KEYCLOAK_CLIENT_SECRET}
  endpoints:
    introspection: ${KEYCLOAK_INTROSPECTION_ENDPOINT}
    token: ${KEYCLOAK_TOKEN_ENDPOINT}
  jwt-converter:
    role-claims: realm_access.roles,resource_access.account.roles
    username-attribute: preferred_username

configuration:
  service:
    email: ${SERVICE_MAIL_USERNAME}
    name: ${SERVICE_NAME:JustedlevHub}
    url: ${SERVICE_URL}
  service-registry:
    url: ${SERVICE_REGISTRY_URL}
