spring:
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    web: trace
    sql: trace
    com:
      justedlev:
        hub: trace
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        security: trace

# Custom properties
configuration:
  activity-time: ${ACTIVITY_TIME:10m}
  offline-after-time: ${OFFLINE_AFTER_TIME:10m}

jstorage:
  client:
    url: ${GATEWAY_HOST}/api/v1/
