server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /api/v1
logging:
  file:
    name: ${logging.file.path}/latest.log
    path: ./.logs
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: user-service
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
      hibernate:
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: ${app-config.service-registry.url}
cloudamqp:
  host: ${CLOUDAMQP_HOST}
  port: ${CLOUDAMQP_PORT}
  password: ${CLOUDAMQP_PASSWORD}
  username: ${CLOUDAMQP_USERNAME}
  virtual-host: ${CLOUDAMQP_VIRTUAL_HOST}
  queue:
    send-template-mail: send-template-mail-queue
management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
# Custom properties
app-config:
  service:
    email: ${SERVICE_MAIL_USERNAME}
    name: ${SERVICE_NAME:JustedlevHub}
    label: "{•...•}"
    url: ${SERVICE_URL}
  service-registry:
    url: ${SERVICE_REGISTRY_URL}