server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
logging:
  file:
    name: ${logging.file.path}/latest.log
    path: ./.logs
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwt-set-uri}
      client:
        registration:
          users-justedlevhub:
            provider: keycloak
            client-id: ${CLIENT_ID}
            client_secret: ${CLIENT_SECRET}
            scope:
              - openid
              - offline_access
              - profile
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${keycloak.issuer-uri}
            jwk-set-uri: ${keycloak.jwt-set-uri}
  devtools:
    restart:
      enabled: true
  application:
    name: users-justedlevhub
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: history
            audit_table_suffix: _history
            revision_field_name: rev_id
            revision_type_field_name: rev_type
            store_data_at_delete: true
            audit_table_prefix:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: users
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: ${app-config.service-registry.url}
cloudamqp:
  host: ${CLOUDAMQP_HOST}
  port: ${CLOUDAMQP_PORT}
  password: ${CLOUDAMQP_PASSWORD}
  username: ${CLOUDAMQP_USERNAME}
  virtual-host: ${CLOUDAMQP_VIRTUAL_HOST}
  queue:
    send-template-mail: send-template-mail-queue
management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
# Custom properties
keycloak:
  issuer-uri: ${ISSUER_URI}
  jwt-set-uri: ${JWKS_URI}
  jwt-converter:
    role-claim-names: realm_access.roles,resource_access.account.roles
    principal-claim-name: preferred_username
app-config:
  service:
    email: ${SERVICE_MAIL_USERNAME}
    name: ${SERVICE_NAME:JustedlevHub}
    label: "{•...•}"
    url: ${SERVICE_URL}
  service-registry:
    url: ${SERVICE_REGISTRY_URL}