spring:
  jpa:
    hibernate:
      ddl-auto: update

# Custom properties
application:
  activity-time: ${ACTIVITY_TIME:10m}
  offline-after-time: ${OFFLINE_AFTER_TIME:10m}

jstorage:
  client:
    url: ${GATEWAY_HOST}/api/v1/
